### ISSUE TITLE
失效了，还维护么？

### ISSUE THREAD

**Issue by mengmo** [zmj1316/comic_spider#1]
```
comic_script
输入漫画地址http://www.dm5.com/manhua-moukexuedechaodiancipao/
地址格式错误
输入漫画地址http://www.dm5.com/m558687/
地址格式错误
输入漫画地址
```

**Comment by mengmo** [comment]
```
comic_script
输入漫画地址http://www.1kkk.com/manhua4246/
D:\PortableApps\Python2\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file D:\PortableApps\Python2\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "D:\PortableApps\comic_script\__main__.py", line 94, in <module>
    chs = s.find_all(attrs={'class': 'sy_nr1 cplist_ullg'})[1]
IndexError: list index out of range
```
```
comic_script
输入漫画地址http://www.1kkk.com/ch99-558687/
D:\PortableApps\Python2\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file D:\PortableApps\Python2\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "D:\PortableApps\comic_script\__main__.py", line 94, in <module>
    chs = s.find_all(attrs={'class': 'sy_nr1 cplist_ullg'})[1]
IndexError: list index out of range
```
```
comic_script
输入漫画地址http://www.1kkk.com/vol11-538603/
D:\PortableApps\Python2\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file D:\PortableApps\Python2\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "D:\PortableApps\comic_script\__main__.py", line 94, in <module>
    chs = s.find_all(attrs={'class': 'sy_nr1 cplist_ullg'})[1]
IndexError: list index out of range
```
```
comic_script
输入漫画地址http://www.1kkk.com/other429661/
D:\PortableApps\Python2\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file D:\PortableApps\Python2\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "D:\PortableApps\comic_script\__main__.py", line 94, in <module>
    chs = s.find_all(attrs={'class': 'sy_nr1 cplist_ullg'})[1]
IndexError: list index out of range
```
```
comic_script
输入漫画地址http://www.1kkk.com/sp8-144849/
D:\PortableApps\Python2\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file D:\PortableApps\Python2\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
Traceback (most recent call last):
  File "D:\PortableApps\comic_script\__main__.py", line 94, in <module>
    chs = s.find_all(attrs={'class': 'sy_nr1 cplist_ullg'})[1]
IndexError: list index out of range
```

**Comment by zmj1316** [comment]
应该不会了，推荐 https://github.com/abc9070410/JComicDownloader

**Comment by mengmo** [comment]
多谢！
看了看，现在我用这个了 https://github.com/kanasimi/work_crawler
